# Generated by Django 4.2.29 on 2026-04-02 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('f_min', models.IntegerField(default=0)),
                ('f_max', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'animal_type',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('morph', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10)),
                ('birth', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('image', models.CharField(default='dummy.jpg', max_length=255)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('updated_date', models.DateField(default=datetime.date.today)),
                ('art', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animaltype')),
            ],
            options={
                'db_table': 'animals',
            },
        ),
    ]
