# Generated by Django 4.2.29 on 2026-04-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeding', '0001_initial'),
        ('animals', '0001_initial'),
        ('terrariums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='default_ft',
            field=models.ForeignKey(blank=True, db_column='default_ft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='feeding.feedingtype'),
        ),
        migrations.AddField(
            model_name='animal',
            name='terrarium',
            field=models.ForeignKey(blank=True, db_column='terrarium', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='terrariums.terrarium'),
        ),
    ]
