# Generated by Django 4.2.29 on 2026-04-02 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('image', models.CharField(default='dummy.jpg', max_length=255)),
            ],
            options={
                'db_table': 'terrariums',
            },
        ),
        migrations.CreateModel(
            name='TerrariumHistoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'terrarium_history_type',
            },
        ),
        migrations.CreateModel(
            name='TerrariumType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'terrarium_type',
            },
        ),
        migrations.CreateModel(
            name='TerrariumLamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp_type', models.CharField(db_column='type', max_length=255)),
                ('watt', models.CharField(blank=True, max_length=50)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('changed', models.DateField(blank=True, null=True)),
                ('terrarium', models.ForeignKey(db_column='terrarium', on_delete=django.db.models.deletion.CASCADE, related_name='lamps', to='terrariums.terrarium')),
            ],
            options={
                'db_table': 'terrarium_lamps',
            },
        ),
        migrations.CreateModel(
            name='TerrariumHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('event', models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='terrariums.terrariumhistorytype')),
                ('terrarium', models.ForeignKey(db_column='terrarium', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='terrariums.terrarium')),
            ],
            options={
                'db_table': 'terrarium_history',
            },
        ),
        migrations.CreateModel(
            name='TerrariumEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('terrarium', models.ForeignKey(db_column='terrarium', on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='terrariums.terrarium')),
            ],
            options={
                'db_table': 'terrarium_equipment',
            },
        ),
        migrations.AddField(
            model_name='terrarium',
            name='terrarium_type',
            field=models.ForeignKey(db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terrariums', to='terrariums.terrariumtype'),
        ),
    ]
