# Generated by Django 4.2.29 on 2026-04-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('terrariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(blank=True, db_column='animal_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='animals.animal')),
                ('terrarium', models.ForeignKey(blank=True, db_column='terrarium_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='terrariums.terrarium')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
