# Generated by Django 4.2.29 on 2026-04-02 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'history_type',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('animal', models.ForeignKey(db_column='animal', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='animals.animal')),
                ('event', models.ForeignKey(db_column='event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='history.historytype')),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
