# Generated by Django 4.2.29 on 2026-04-02 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('weight', 'Weight'), ('text', 'Text'), ('size', 'Size')], max_length=50)),
                ('detail', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'feeding_type',
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('animal', models.ForeignKey(db_column='animal', on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='animals.animal')),
                ('feeding_type', models.ForeignKey(db_column='type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedings', to='feeding.feedingtype')),
            ],
            options={
                'db_table': 'feedings',
            },
        ),
    ]
